---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt repository
      apt_repository: repo={{ item }} state=present
      with_items:
        - ppa:nginx/stable
        - ppa:git-core/ppa

    - name: Run apt-get update
      apt: update_cache=yes

    - name: build dep for emacs24.5
      apt: pkg=emacs24 state=build-dep

    - name: Install favorate tools
      apt: pkg={{ item }} state=latest
      with_items:
        - build-essential
        - compiz
        - compiz-plugins
        - compizconfig-settings-manager
        - git
        - apache2-utils
        - autojump
        - docker
        - htop
        - ispell
        - libtinfo-dev
        - silversearcher-ag
        - tmux
        - tree
        - wmctrl

    # extra Python modules
    - name: Install python modules
      pip: name={{ item }}
      with_items:
        - epc
        - jedi
